openapi: 3.0.0
info:
  title: Chat API
  description: AI 문제풀이 대화 관리 API
  version: 1.0.0
paths:
  /chatrooms:
    post:
      summary: 채팅방 조회 또는 생성
      description: 문제 ID와 세션 키를 기반으로 채팅방을 조회합니다. 채팅방이 존재하지 않으면 새로 생성한 후, 해당 채팅방의 채팅 로그를 반환합니다.
      tags:
        - 채팅
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                problem_id:
                  type: integer
                  description: 문제 ID
                session_key:
                  type: string
                  description: 세션 키 (대화 식별자)
              required:
                - problem_id
                - session_key
      responses:
        '200':
          description: 채팅방 조회 또는 생성 성공 및 채팅 로그 반환
          content:
            application/json:
              schema:
                type: object
                properties:
                  isSuccess:
                    type: boolean
                    example: true
                  code:
                    type: integer
                    example: 2000
                  message:
                    type: string
                    example: "채팅방 조회 또는 생성 성공!"
                  result:
                    type: object
                    properties:
                      roomId:
                        type: integer
                        description: 채팅방 ID
                        example: 1
                      logs:
                        type: array
                        description: 채팅 로그 데이터
                        items:
                          type: object
                          properties:
                            chatId:
                              type: integer
                              description: 채팅 로그 ID
                              example: 1
                            message:
                              type: string
                              description: 대화 내용
                              example: "안녕하세요"
                            speaker:
                              type: string
                              description: 발화자 (user 또는 chatgpt)
                              example: "user"
                            sequence:
                              type: integer
                              description: 대화 순서
                              example: 1
                            created_at:
                              type: string
                              format: datetime
                              description: 대화 생성 시간
                              example: "2023-08-26T12:34:56Z"
        '400':
          description: 잘못된 요청
          content:
            application/json:
              schema:
                type: object
                properties:
                  isSuccess:
                    type: boolean
                    example: false
                  code:
                    type: string
                    example: "COMMON001"
                  message:
                    type: string
                    example: "잘못된 요청입니다."
                  result:
                    type: string
                    example: "잘못된 요청 본문"
        '500':
          description: 서버 오류
          content:
            application/json:
              schema:
                type: object
                properties:
                  isSuccess:
                    type: boolean
                    example: false
                  code:
                    type: string
                    example: "SERVER001"
                  message:
                    type: string
                    example: "서버 오류가 발생했습니다."
                  result:
                    type: string
                    example: "서버 오류"

  /chatrooms/chats:
    post:
      summary: 채팅 메시지 추가
      description: 특정 채팅방에 새로운 채팅 메시지를 추가합니다.
      tags:
        - 채팅
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                room_id:
                  type: integer
                  description: 채팅방 ID
                message:
                  type: string
                  description: 대화 내용
                speaker:
                  type: string
                  description: 발화자 (user 또는 chatgpt)
                  enum:
                    - user
                    - chatgpt
              required:
                - room_id
                - message
                - speaker
      responses:
        '200':
          description: 채팅 메시지 추가 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  isSuccess:
                    type: boolean
                    example: true
                  code:
                    type: integer
                    example: 2000
                  message:
                    type: string
                    example: "채팅 메시지가 성공적으로 추가되었습니다."
                  result:
                    type: object
                    properties:
                      chatId:
                        type: integer
                        description: 생성된 채팅 로그 ID
                        example: 1
        '400':
          description: 잘못된 요청
          content:
            application/json:
              schema:
                type: object
                properties:
                  isSuccess:
                    type: boolean
                    example: false
                  code:
                    type: string
                    example: "COMMON001"
                  message:
                    type: string
                    example: "잘못된 요청입니다."
                  result:
                    type: string
                    example: "잘못된 요청 본문"
        '500':
          description: 서버 오류
          content:
            application/json:
              schema:
                type: object
                properties:
                  isSuccess:
                    type: boolean
                    example: false
                  code:
                    type: string
                    example: "SERVER001"
                  message:
                    type: string
                    example: "서버 오류가 발생했습니다."
                  result:
                    type: string
                    example: "서버 오류"