openapi: 3.0.0
info:
  title: 홈 관련 API
  version: 1.0.0

paths:
  /folders:
    get:
      summary: 전체 폴더 조회하기
      description: 사용자가 보유하고 있는 모든 폴더 목록을 조회합니다.
      tags:
        - 홈
      responses:
        '200':
          description: 폴더 목록 조회 성공
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    folderId:
                      type: string
                      description: 폴더 ID
                    folderName:
                      type: string
                      description: 폴더 이름
        '400':
          description: 잘못된 요청
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "잘못된 요청 본문"

  /folders/order:
    patch:
      summary: 전체 폴더 배치 조정하기
      description: 폴더 디스플레이 순서를 조정합니다.
      tags:
        - 홈
      parameters:
        - name: order
          in: query
          required: true
          schema:
            type: array
            items:
              type: string
              description: 폴더 ID
            description: 새 폴더 순서 배열 (배열의 순서가 새로운 폴더 배치를 나타냅니다.)
      responses:
        '200':
          description: 폴더 순서 조정 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "폴더 순서 조정 성공"

  /folders/{folderId}:
    patch:
      summary: 폴더 이름 수정하기
      description: 폴더의 이름을 수정합니다.
      tags:
        - 홈
      parameters:
        - name: folderId
          in: path
          required: true
          schema:
            type: string
            description: 폴더 ID
        - name: folderName
          in: query
          required: true
          schema:
            type: string
            description: 수정할 폴더 이름
      responses:
        '200':
          description: 폴더 이름 수정 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "폴더 이름 수정 성공"
        '400':
          description: 잘못된 요청
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "잘못된 요청 본문"
        '404':
          description: 찾을 수 없음
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "데이터를 찾을 수 없습니다."


    delete:
      summary: 폴더 삭제하기
      description: 폴더를 삭제하면 그 안에 있는 문제들도 모두 삭제됩니다.
      tags:
        - 홈
      parameters:
        - name: folderId
          in: path
          required: true
          schema:
            type: string
            description: 폴더 ID
      responses:
        '204':
          description: 폴더 및 폴더 내 문제 삭제 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "폴더 및 폴더 내 문제 삭제 성공"
        '404':
          description: 찾을 수 없음
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "데이터를 찾을 수 없습니다."

  /folders/{folderId}/problems:
    get:
      summary: 폴더 속 문제 미리보기
      description: 폴더를 선택하면 해당 폴더 안에 있는 문제들을 볼 수 있습니다.
      tags:
        - 홈
      parameters:
        - name: folderId
          in: path
          required: true
          schema:
            type: string
            description: 폴더 ID
      responses:
        '200':
          description: 폴더 속 문제 미리보기 조회 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  folderName:
                    type: string
                    description: 폴더 이름
                  problems:
                    type: array
                    items:
                      type: object
                      properties:
                        problemId:
                          type: string
                          description: 문제 ID
                        problemText:
                          type: string
                          description: 문제 텍스트
                        problemImage:
                          type: string
                          format: uri
                          description: 문제 이미지 URL
        '404':
          description: 찾을 수 없음
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "데이터를 찾을 수 없습니다."
  /folders/problems:
    post:
      tags:
        - 홈
      summary: 문제 추가하기
      description: 문제 추가하기
      parameters:
      - name: token
        in: header
        required: true
        schema:
          properties:
            Authorization:
              type: string
              description: 헤더에 토큰을 입력

      - name: addProblem
        in: body
        required: true
        schema:
          properties:
            folderId:
              type: integer
              description: 폴더 ID
              example: 1
            userId:
              type: integer
              description: 사용자 ID
              example: 1
            subscriptionPlan:
              type: boolean
              description: 구독 계획
              example: true
            problemText:
               type: string
               description: 문제 텍스트
               example: "2+4"
            answer:
              type: string
              description: 문제 정답
              example: "6"
            mainCategory:
              type: string
              description: 대분류
              example: "수학"
            category:
              type: string
              description: 중분류
              example: "미적분"
            subCategory:
              type: string
              description: 소분류
              example: "함수의 극한"
            photos:
              type: array
              items:
                type: object
                properties:
                  photoUrl:
                    type: string
                    format: uri
                    description: 사진 URL
                    example: "http://example.com/photo1.jpg"
                  photoType:
                    type: string
                    description: 사진 유형
                    example: "문제"     
               
      responses:
        '200':
          description: 문제 추가 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  issuccess:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: 문제 추가하기 성공             
        '400':
          description: 문제 추가하기 실패
          content:
            application/json:
              schema:
                type: object
                properties:
                  errorMessage:
                    type: string
                    example: Invalid request

  /problems/scale:
    patch:
      summary: 문제 미리보기 스케일 설정
      description: 특정 폴더 안 문제들을 조회할 수 있는 화면에서 확대 축소하여 가로 줄에서 디스플레이할 문제 수를 조절합니다.
      tags:
        - 홈
      parameters:
        - name: scale
          in: query
          required: true
          schema:
            type: number
            format: float
            description: 확대/축소 비율. 예를 들어, 1은 기본 크기, 2는 2배 확대, 0.5는 50% 축소를 의미합니다.
      responses:
        '200':
          description: 스케일 설정 성공
          content:
           application/json:
             schema:
               type: object
               properties:
                 scale:
                   type: number
                   format: float
                   description: 현재 설정된 확대/축소 비율
               example:
                 scale: 1.5              
        '400':
          description: 잘못된 요청
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "잘못된 요청 본문"
        '404':
          description: 찾을 수 없음
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "데이터를 찾을 수 없습니다."

  /problems/search:
    get:
      summary: 문제 검색하기 (구독)
      description: 전체 문제 또는 특정 폴더 안 문제를 검색합니다. `folderId` 파라미터가 제공되지 않으면 전체 문제를 검색하며, 제공되면 해당 폴더 내 문제만 검색합니다.
      tags:
        - 홈
      parameters:
        - name: query
          in: query
          required: true
          schema:
            type: string
            description: 검색할 텍스트. 문제 텍스트에서 이 텍스트를 포함하는 문제를 찾습니다.
        - name: folderId
          in: query
          schema:
            type: string
            description: (선택 사항) 검색할 폴더의 ID. 이 파라미터가 제공되면 해당 폴더 내에서만 검색이 수행됩니다.
      responses:
        '200':
          description: 문제 검색 성공
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    problemId:
                      type: string
                      description: 문제 ID
                    problemImage:
                        type: string
                        format: uri
                        description: 문제 이미지 URL
                    problemText:
                        type: string
                        description: 문제 텍스트
        '400':
          description: 잘못된 요청
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "잘못된 요청 본문"
        '403':
          description: 구독 계정이 아닐 경우 접근 거부
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "구독 계정만 이용 가능합니다."
        '404':
          description: 찾을 수 없음
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "데이터를 찾을 수 없습니다."             

  /problems/{problemId}:
    get:
      summary: 문제 조회하기
      description: 문제의 세부 정보를 조회합니다.
      tags:
        - 홈
      parameters:
        - name: problemId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: 문제 조회 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  problemId:
                    type: string
                  problemImage:
                    type: string
                    format: uri
                    description: 문제 이미지 URL
                  answer:
                    type: string
                  solutionImage:
                    type: string
                    format: uri
                    description: 풀이 과정 이미지 URL
                  passageImage:
                    type: string
                    format: uri
                    description: 지문 이미지 URL
                  additionalProblemImage:
                    type: string
                    format: uri
                    description: 추가 문제 이미지 URL
                  problemText:
                    type: string
                    description: (구독) 문제 텍스트
                  problemType:
                    type: string
                    description: 문제 유형
                  statistics:
                    type: object
                    properties:
                      wrongCount:
                        type: integer
                        description: 틀린 횟수
                      solvedCount:
                        type: integer
                        description: 맞은 횟수
                required:
                  - problemImage
                  - answer
        '403':
         description: 구독 계정이 아닐 경우 접근 거부
         content:
           application/json:
             schema:
               type: object
               properties:
                 message:
                   type: string
                   example: "구독 계정만 이용 가능합니다."
        '404':
          description: 찾을 수 없음
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "데이터를 찾을 수 없습니다."

  /problems/{problemId}/edit:
    patch:
      summary: 문제 수정하기
      description: 문제의 세부 정보를 수정합니다.
      tags:
        - 홈
      parameters:
        - name: problemId
          in: path
          required: true
          schema:
            type: string
            description: 문제 ID
        - name: problemImage
          in: query
          schema:
            type: string
            format: binary
            description: 문제 이미지 파일
        - name: answer
          in: query
          schema:
            type: string
            description: 문제 정답
        - name: solutionImage
          in: query
          schema:
            type: string
            format: binary
            description: 풀이 과정 이미지 
        - name: passageImage
          in: query
          schema:
            type: string
            format: binary
            description: 지문 이미지 파일
        - name: additionalProblemImage
          in: query
          schema:
            type: array
            format: binary
            items:
              type: string
              format: binary
            description: 추가 문제 이미지 파일(여러장 가능)
        - name: problemText
          in: query
          schema:
            type: string
            description: 문제 텍스트 (구독)
        - name: problemType
          in: query
          schema:
            type: string
            description: 문제 유형
      responses:
        '200':
          description: 문제 수정 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "문제 수정 성공"
        '400':
          description: 잘못된 요청
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "잘못된 요청 본문"
        '403':
         description: 구독 계정이 아닐 경우 접근 거부
         content:
           application/json:
             schema:
               type: object
               properties:
                 message:
                   type: string
                   example: "구독 계정만 이용 가능합니다."
        '404':
          description: 찾을 수 없음
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "데이터를 찾을 수 없습니다."

  /problems/{problemId}/ai-solution:
    post:
      summary: AI 문제 풀이 (구독)
      description: ChatGPT API를 활용하여 문제 풀이를 제공합니다.
      tags:
        - 홈
      parameters:
        - name: problemId
          in: path
          required: true
          schema:
            type: string
            description: 문제 ID
        - name: prompt
          in: query
          required: false
          schema:
            type: string
            description: 텍스트 프롬프트
        - name: image
          in: query
          required: false
          schema:
            type: string
            format: binary
            description: 문제 이미지를 업로드합니다. 카메라 촬영 또는 갤러리에서 선택된 이미지를 포함할 수 있습니다.
      responses:
        '200':
          description: AI 문제 풀이 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  response:
                    type: string
                    description: AI가 생성한 문제 풀이 텍스트
        '400':
          description: 잘못된 요청
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "잘못된 요청 본문"
        '403':
         description: 구독 계정이 아닐 경우 접근 거부
         content:
           application/json:
             schema:
               type: object
               properties:
                 message:
                   type: string
                   example: "구독 계정만 이용 가능합니다."
        '404':
          description: 찾을 수 없음
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "데이터를 찾을 수 없습니다."
        '500':
          description: 서버 오류 (예-ChatGPT API 호출 실패)
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "서버 오류가 발생했습니다. 잠시 후 다시 시도해 주세요."
