openapi: 3.0.0
info:
  title: 통계 관련 API
  version: 1.0.0

paths:                  
  /problems/statistics/mistakes:
    get:
      summary: 많이 틀린 문제 순으로 조회
      description: 사용자가 틀린 문제를 틀린 횟수에 따라 나열합니다.
      tags:
        - 통계
      responses:
        '200':
          description: 많이 틀린 문제 조회 성공
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    problemId:
                      type: string
                      description: 문제 ID
                    problemImage:
                      type: string
                      format: uri
                      description: 문제 이미지 URL
                    mistakeCount:
                      type: integer
                      description: 틀린 횟수
        '400':
          description: 잘못된 요청
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "잘못된 요청 본문입니다."
        '404':
          description: 찾을 수 없음
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "데이터를 찾을 수 없습니다."
          
  /problems/statistics/types:
    get:
      summary: 자주 틀린 과목 및 유형 조회
      description: 자주 틀린 과목과 문제 유형을 분석하여 표시합니다.
      tags:
        - 통계
      responses:
        '200':
          description: 자주 틀린 과목 및 유형 조회 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  mainCategory:
                    type: string
                    description: 대분류
                    example: 수학
                  category:
                    type: string
                    description: 조회된 과목의 이름(중분류)
                    example: 미적분
                  subCategories:
                    type: array
                    items:
                      type: object
                      properties:
                        subCategory:
                          type: string
                          nullable: true
                          description: 문제 유형(소분류)
                          example: "뺄셈"
                        totalIncorrect:
                          type: integer
                          description: 해당 문제 유형에서의 총 틀린 횟수
                          example: 3
                required:
                  - category
                  - subCategories
        '400':
          description: 잘못된 요청
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "잘못된 요청 본문입니다."
        '404':
          description: 찾을 수 없음
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "데이터를 찾을 수 없습니다."
  /problems/statistics/ratios/{categoryId}:
    get:
      summary: 문제 유형별 틀린 비율 조회
      description: 특정 카테고리의 하위 문제 유형별 틀린 비율을 조회합니다.
      tags:
        - 통계
      parameters:
        - in: path
          name: categoryId
          required: true
          schema:
            type: integer
          description: 조회할 카테고리의 ID
          example: 1
      responses:
        '200':
          description: 문제 유형별 틀린 비율 조회 성공
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    subCategory:
                      type: string
                      nullable: true
                      description: 문제 유형(소분류)
                      example: "뺄셈"
                    incorrectPercentage:
                      type: string
                      description: 틀린 비율 (백분율로 표현)
                      example: "27.27273"

        '400':
          description: 잘못된 요청
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "잘못된 요청 본문입니다."
        '404':
          description: 찾을 수 없음
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "데이터를 찾을 수 없습니다."
