openapi: 3.0.0
info:
  title: 학습하기(문제풀기) 관련 API
  version: 1.0.0

paths: 
  /studies/folders/{folderId}:
    get:
      summary: 학습용 폴더 선택하기
      description: 학습하기 탭에서 문제를 풀 폴더를 선택합니다.
      tags:
        - 학습하기
      parameters:
        - name: folderId
          in: path
          required: true
          schema:
            type: string
            description: 폴더 ID
      responses:
        '200':
          description: 폴더 선택 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "폴더 선택 완료"
                  folderId:
                    type: string
                    description: 선택된 폴더 ID
                    example: "1"
        '404':
          description: 찾을 수 없음
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "데이터를 찾을 수 없습니다."
        '400':
          description: 잘못된 요청
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "잘못된 요청 본문입니다."

  /studies/folders/{folderId}/problems/{problemIndex}:
    get:
      summary: 학습용 문제 조회하기
      description: 학습하기 탭에서 특정 폴더 내 문제를 조회합니다.
      tags:
        - 학습하기
      parameters:
        - name: folderId
          in: path
          required: true
          schema:
            type: string
            description: 폴더 ID
        - name: problemIndex
          in: path
          required: true
          schema:
            type: integer
            description: 문제 인덱스(0부터 시작)
      responses:
        '200':
          description: 문제 조회 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  problemId:
                    type: string
                  problemImage:
                    type: string
                    format: uri
                    description: 문제 이미지 URL
                  folderName:
                    type: string
                    description: 폴더의 이름
                required:
                  - problemImage
        '404':
          description: 찾을 수 없음
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "데이터를 찾을 수 없습니다."

  /studies/folders/{folderId}/problems/{problemId}/check-answer:
    post:
      summary: 정답 확인하기
      description: 사용자가 정답을 확인하고 맞췄는지 기록합니다.
      tags:
        - 학습하기
      parameters:
        - name: folderId
          in: path
          required: true
          schema:
            type: string
            description: 폴더 ID
        - name: problemId
          in: path
          required: true
          schema:
            type: string
            description: 문제 ID
        - name: swipeDirection
          in: query
          required: true
          schema:
            type: string
            enum:
              - right
              - left
            description: 스와이프 방향 ('right'는 정답, 'left'는 정답이 아님)
            
      responses:
        '200':
          description: 정답 확인 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: 문제 풀이 상태 (예- '미완료', '맞은 문제', '틀린 문제')
                  correctAnswer:
                    type: string
                    description: 실제 정답
        '400':
          description: 잘못된 요청
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "잘못된 요청 본문입니다."
        '404':
          description: 찾을 수 없음
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "데이터를 찾을 수 없습니다."
        '500':
          description: 서버 오류
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "서버 오류 발생"

  /studies/folders/{folderId}/progress:
    get:
      summary: 풀이 진척도 확인하기
      description: 폴더 내 풀이 진척도를 확인합니다.
      tags:
        - 학습하기
      parameters:
        - name: folderId
          in: path
          required: true
          schema:
            type: string
            description: 폴더 ID
      responses:
        '200':
          description: 풀이 진척도 조회 성공
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    problemId:
                      type: string
                      description: 문제 ID
                    status:
                      type: string
                      enum: 
                        - 미완료
                        - 맞은 문제
                        - 틀린 문제
                      description: 문제 상태  
        '500':
          description: 서버 오류
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string