openapi: 3.0.0
info:
  title: 구독 관련 API
  version: 1.0.0

paths:
  /subscription/approve:
    patch:
      tags:
        - 구독
      summary: 구독하기
      responses:
        "200":
          description: 구독이 성공적으로 시작
          content:
            application/json:
              schema:
                type: object
                properties:
                  isSuccess:
                    type: boolean
                    example: true
                  code:
                    type: string
                    example: SUBSCRIPTION2001
                  message:
                    type: string
                    example: 구독하기 성공입니다.
                  result:
                    type: object
                    nullable: true
        "400":
          description: 구독 실패
          content:
            application/json:
              schema:
                type: object
                properties:
                  errorMessage:
                    type: string
                    example: "Invalid request"

  /subscription/cancel:
    patch:
      tags:
        - 구독
      summary: 구독 취소
      responses:
        "200":
          description: 구독이 성공적으로 취소되었습니다.
          content:
            application/json:
              schema:
                type: object
                properties:
                  isSuccess:
                    type: boolean
                    example: true
                  code:
                    type: string
                    example: SUBSCRIPTION2002
                  message:
                    type: string
                    example: 구독이 성공적으로 취소되었습니다.
                  result:
                    type: object
                    nullable: true
        "400":
          description: 구독 취소 실패
          content:
            application/json:
              schema:
                type: object
                properties:
                  errorMessage:
                    type: string
                    example: "Invalid request"
