paths:
  /subscription/approve:
    patch:
      summary: 구독 승인 및 결제 처리
      description: 사용자 구독을 승인하고, 토스 결제 API를 통해 결제를 처리합니다.
      tags:
        - 구독
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                paymentKey:
                  type: string
                  description: 결제를 위한 토스 결제 키
                  example: "some_payment_key"
                orderId:
                  type: string
                  description: 주문 ID
                  example: "order_123456"
                amount:
                  type: integer
                  description: 결제 금액
                  example: 10000
              required:
                - paymentKey
                - orderId
                - amount
      responses:
        '200':
          description: 구독 승인 및 결제 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  isSuccess:
                    type: boolean
                    example: true
                  code:
                    type: integer
                    example: 2000
                  message:
                    type: string
                    example: "구독 승인 및 결제 성공!"
                  result:
                    type: object
                    description: 결제와 구독 상태 업데이트 결과
        '500':
          description: 서버 오류
          content:
            application/json:
              schema:
                type: object
                properties:
                  isSuccess:
                    type: boolean
                    example: false
                  code:
                    type: integer
                    example: 5000
                  message:
                    type: string
                    example: "내부 서버 오류"
  
  /subscription/cancel:
    patch:
      summary: 구독 취소
      description: 사용자의 구독을 취소합니다.
      tags:
        - 구독
      responses:
        '200':
          description: 구독 취소 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  isSuccess:
                    type: boolean
                    example: true
                  code:
                    type: integer
                    example: 2000
                  message:
                    type: string
                    example: "구독 취소 성공!"
        '500':
          description: 서버 오류
          content:
            application/json:
              schema:
                type: object
                properties:
                  isSuccess:
                    type: boolean
                    example: false
                  code:
                    type: integer
                    example: 5000
                  message:
                    type: string
                    example: "내부 서버 오류"
  /subscription/get-client-key:
    get:
      summary: 클라이언트 키 반환
      description: 토스 결제를 위해 필요한 클라이언트 키를 반환합니다.
      tags:
        - 구독
      responses:
        '200':
          description: 클라이언트 키 반환 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  clientKey:
                    type: string
                    description: 클라이언트 키
                    example: "test_ck_xxx"
        '500':
          description: 서버 오류
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: "ClientKey가 설정되지 않았습니다."

